#ifndef CSPICE_RUNNER_V2_CALL_SPEC_H
#define CSPICE_RUNNER_V2_CALL_SPEC_H

#include "cspice_runner_common.h"

typedef enum {
  V2_SPICE_CALL_UNKNOWN = 0,
  V2_SPICE_CALL_CARD,
  V2_SPICE_CALL_SIZE,
  V2_SPICE_CALL_SCARD,
  V2_SPICE_CALL_SSIZE,
  V2_SPICE_CALL_VALID,
  V2_SPICE_CALL_DSKOBJ,
  V2_SPICE_CALL_DSKSRF,
  V2_SPICE_CALL_DSKGD,
  V2_SPICE_CALL_DSKB02,
  V2_SPICE_CALL_DSKMI2,
  V2_SPICE_CALL_DSKOPN,
  V2_SPICE_CALL_DSKW02,
  V2_SPICE_CALL_READ_VIRTUAL_OUTPUT,
} V2SpiceCallId;

typedef enum {
  V2_SPICE_CALL_ARG_INT_EXPR = 0,
  V2_SPICE_CALL_ARG_CELL_REF,
  V2_SPICE_CALL_ARG_CELL_OR_WINDOW_REF,
  V2_SPICE_CALL_ARG_PATH_EXPR,
  V2_SPICE_CALL_ARG_DAS_HANDLE_REF,
  V2_SPICE_CALL_ARG_DLA_DESCR_REF,
} V2SpiceCallArgKind;

typedef enum {
  V2_SPICE_CALL_OUTPUT_FORBIDDEN = 0,
  V2_SPICE_CALL_OUTPUT_AS_INT,
  V2_SPICE_CALL_OUTPUT_AS_DSK_DESCR,
  V2_SPICE_CALL_OUTPUT_NAMED_DSKB02,
} V2SpiceCallOutputKind;

#define V2_SPICE_CALL_MAX_ARITY 3

typedef struct {
  V2SpiceCallId id;
  const char *name;
  int arity;
  V2SpiceCallArgKind argKinds[V2_SPICE_CALL_MAX_ARITY];
  unsigned int nonNegativeIntArgMask;
  V2SpiceCallOutputKind outputKind;
} V2SpiceCallSpec;

const V2SpiceCallSpec *v2_lookup_spice_call_spec(const char *name);

#endif
