#ifndef CSPICE_RUNNER_CALL_REGISTRY_H
#define CSPICE_RUNNER_CALL_REGISTRY_H

#include "cspice_runner_common.h"

typedef enum {
  CALL_NONE = 0,

  // time
  CALL_TIME_STR2ET,
  CALL_TIME_ET2UTC,

  // time (misc)
  CALL_TIME_SPICE_VERSION,
  CALL_TIME_TKVRSN,
  CALL_TIME_TIMOUT,
  CALL_TIME_DELTET,
  CALL_TIME_UNITIM,
  CALL_TIME_TPARSE,
  CALL_TIME_TPICTR,
  CALL_TIME_TIMDEF,

  // ids-names
  CALL_BODN2C,
  CALL_BODC2N,
  CALL_BODC2S,
  CALL_BODS2C,
  CALL_BODDEF,
  CALL_BODFND,
  CALL_BODVAR,

  // frames
  CALL_NAMFRM,
  CALL_FRMNAM,
  CALL_CIDFRM,
  CALL_CNMFRM,
  CALL_FRINFO,
  CALL_CCIFRM,
  CALL_PXFORM,
  CALL_SXFORM,

  // coords-vectors
  CALL_AXISAR,
  CALL_GEOREC,
  CALL_LATREC,
  CALL_MTXV,
  CALL_MXM,
  CALL_MXV,
  CALL_RECGEO,
  CALL_RECLAT,
  CALL_RECSPH,
  CALL_ROTATE,
  CALL_ROTMAT,
  CALL_SPHREC,
  CALL_VADD,
  CALL_VCRSS,
  CALL_VDOT,
  CALL_VHAT,
  CALL_VMINUS,
  CALL_VNORM,
  CALL_VSCL,
  CALL_VSUB,

  // ephemeris
  CALL_SPKEZR,
  CALL_SPKPOS,
  CALL_SPKEZ,
  CALL_SPKEZP,
  CALL_SPKGEO,
  CALL_SPKGPS,
  CALL_SPKSSB,
  CALL_SPKPDS,
  CALL_SPKUDS,
  CALL_SPKSFS,

  // file-io
  CALL_FILE_IO_EXISTS,
  CALL_FILE_IO_GETFAT,
  CALL_FILE_IO_DAFOPR,
  CALL_FILE_IO_DAFCLS,
  CALL_FILE_IO_DAFBFS,
  CALL_FILE_IO_DAFFNA,
  CALL_FILE_IO_DASOPR,
  CALL_FILE_IO_DASCLS,
  CALL_FILE_IO_DLAOPN,
  CALL_FILE_IO_DLABFS,
  CALL_FILE_IO_DLAFNS,
  CALL_FILE_IO_DLACLS,



  // kernels
  CALL_KERNELS_FURNSH,
  CALL_KERNELS_UNLOAD,
  CALL_KERNELS_KCLEAR,
  CALL_KERNELS_KTOTAL,
  CALL_KERNELS_KDATA,
  CALL_KERNELS_KINFO,
  CALL_KERNELS_KXTRCT,
  CALL_KERNELS_KPLFRM,

  // cells-windows
  CALL_CELLS_WINDOWS_INSRTI,
  CALL_CELLS_WINDOWS_INSRTD,
  CALL_CELLS_WINDOWS_INSRTC,
  CALL_CELLS_WINDOWS_WNINSD,
  CALL_CELLS_WINDOWS_WNCARD,
  CALL_CELLS_WINDOWS_WNFETD,
  CALL_CELLS_WINDOWS_WNVALD,

  // kernel-pool
  CALL_GDPOOL,
  CALL_GIPOOL,
  CALL_GCPOOL,
  CALL_GNPOOL,
  CALL_DTPOOL,
  CALL_PDPOOL,
  CALL_PIPOOL,
  CALL_PCPOOL,
  CALL_SWPOOL,
  CALL_CVPOOL,
  CALL_EXPOOL,
} CallId;

CallId parse_call_id(const char *call);

#endif
