/*
 * AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by: pnpm -C packages/parity-checking run generate:v2-spice-calls
 * Source of truth: catalogs/v2-spice-call-manifest.json
 */

#include "cspice_runner_v2_spice_calls_generated.h"

#include "cspice_runner_json_emit.h"
#include "cspice_runner_error.h"
#include "cspice_runner_temp_files.h"
#include "cspice_runner_v2_fixtures.h"

#define SPEC_ROW(_name, _arity, _k0, _k1, _k2, _nonNegMask, _outKind, _invokeLane) \
  {                                                                               \
      .name = (_name),                                                            \
      .arity = (_arity),                                                          \
      .argKinds = {(_k0), (_k1), (_k2)},                                          \
      .nonNegativeIntArgMask = (_nonNegMask),                                     \
      .outputKind = (_outKind),                                                   \
      .invokeLane = (_invokeLane),                                                \
  }

static const V2SpiceCallSpec V2_SPICE_CALL_SPECS[] = {
    SPEC_ROW("card_c",
             1,
             V2_SPICE_CALL_ARG_CELL_OR_WINDOW_REF,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_AS_INT,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("size_c",
             1,
             V2_SPICE_CALL_ARG_CELL_OR_WINDOW_REF,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_AS_INT,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("scard_c",
             2,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_CELL_OR_WINDOW_REF,
             V2_SPICE_CALL_ARG_INT_EXPR,
             1U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("ssize_c",
             2,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_CELL_OR_WINDOW_REF,
             V2_SPICE_CALL_ARG_INT_EXPR,
             1U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("valid_c",
             3,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_CELL_OR_WINDOW_REF,
             3U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("dskobj_c",
             2,
             V2_SPICE_CALL_ARG_PATH_EXPR,
             V2_SPICE_CALL_ARG_CELL_REF,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("dsksrf_c",
             3,
             V2_SPICE_CALL_ARG_PATH_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_CELL_REF,
             0U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("dskgd_c",
             2,
             V2_SPICE_CALL_ARG_DAS_HANDLE_REF,
             V2_SPICE_CALL_ARG_DLA_DESCR_REF,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_AS_DSK_DESCR,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("dskb02_c",
             2,
             V2_SPICE_CALL_ARG_DAS_HANDLE_REF,
             V2_SPICE_CALL_ARG_DLA_DESCR_REF,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_NAMED_DSKB02,
             V2_SPICE_CALL_INVOKE_DIRECT),

    SPEC_ROW("dskmi2_c",
             0,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_LEGACY_DSKMI2),

    SPEC_ROW("dskopn_c",
             0,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_LEGACY_DSKOPN),

    SPEC_ROW("dskw02_c",
             0,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_LEGACY_DSKW02),

    SPEC_ROW("readVirtualOutput",
             1,
             V2_SPICE_CALL_ARG_PATH_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             V2_SPICE_CALL_ARG_INT_EXPR,
             0U,
             V2_SPICE_CALL_OUTPUT_FORBIDDEN,
             V2_SPICE_CALL_INVOKE_READ_VIRTUAL_OUTPUT),
};

#undef SPEC_ROW

const V2SpiceCallSpec *v2_lookup_spice_call_spec(const char *name) {
  const int count = (int)(sizeof(V2_SPICE_CALL_SPECS) / sizeof(V2_SPICE_CALL_SPECS[0]));
  for (int i = 0; i < count; i++) {
    if (strcmp(V2_SPICE_CALL_SPECS[i].name, name) == 0) {
      return &V2_SPICE_CALL_SPECS[i];
    }
  }

  return NULL;
}

static bool v2_strdup_json_token(const char *json, const jsmntok_t *tok,
                                 char **out) {
  char detail[256];
  detail[0] = '\0';
  jsmn_strdup_err_t err = jsmn_strdup(json, tok, out, detail, sizeof(detail));
  if (err == JSMN_STRDUP_OK) {
    return true;
  }

  if (err == JSMN_STRDUP_INVALID) {
    write_error_json_ex("invalid_request", "Invalid JSON string escape",
                        detail[0] ? detail : NULL, NULL, NULL, NULL);
  } else {
    write_error_json("Out of memory", NULL, NULL, NULL);
  }

  return false;
}

static bool v2_write_spice_failure(const char *messagePrefix) {
  char shortMsg[1841];
  char longMsg[1841];
  char traceMsg[1841];
  capture_spice_error(shortMsg, sizeof(shortMsg), longMsg, sizeof(longMsg),
                      traceMsg, sizeof(traceMsg));
  write_error_json_ex("spice_error", messagePrefix, NULL, shortMsg, longMsg,
                      traceMsg);
  return false;
}

static bool v2_execute_dskopn_legacy_call(void) {
  char tempPath[PATH_MAX];
  char detail[256];
  detail[0] = '\0';
  int tempFd = -1;
  if (!build_file_io_temp_path("v2-dskopn", ".bds", tempPath,
                               sizeof(tempPath), &tempFd, detail,
                               sizeof(detail))) {
    write_error_json_ex("invalid_request", "Failed to create DSK temp path",
                        detail[0] ? detail : NULL, NULL, NULL, NULL);
    return false;
  }

  if (tempFd >= 0) {
    close(tempFd);
    tempFd = -1;
  }
  unlink(tempPath);

  SpiceInt handle = 0;
  dskopn_c(tempPath, "TSPICE", 0, &handle);
  if (failed_c() == SPICETRUE) {
    unlink(tempPath);
    return v2_write_spice_failure("SPICE error in dskopn_c");
  }

  dascls_c(handle);
  if (failed_c() == SPICETRUE) {
    unlink(tempPath);
    return v2_write_spice_failure("SPICE error in dascls_c");
  }

  unlink(tempPath);
  return true;
}

static bool v2_execute_dskmi2_legacy_call(void) {
  if ((size_t)DSK_MINIMAL_WORKSZ > SIZE_MAX / sizeof(SpiceInt[2])) {
    write_error_json("Out of memory", NULL, NULL, NULL);
    return false;
  }

  SpiceInt(*work)[2] = (SpiceInt(*)[2])malloc(sizeof(SpiceInt[2]) *
                                              (size_t)DSK_MINIMAL_WORKSZ);
  if (work == NULL) {
    write_error_json("Out of memory", NULL, NULL, NULL);
    return false;
  }

  SpiceDouble spaixd[SPICE_DSK02_IXDFIX];
  SpiceInt spaixi[DSK_MINIMAL_SPXISZ];

  dskmi2_c((SpiceInt)DSK_MINIMAL_NV,
           (SpiceDouble(*)[3])DSK_MINIMAL_VERTICES,
           (SpiceInt)DSK_MINIMAL_NP,
           (SpiceInt(*)[3])DSK_MINIMAL_PLATES,
           0.2,
           5,
           (SpiceInt)DSK_MINIMAL_WORKSZ,
           (SpiceInt)DSK_MINIMAL_VOXPSZ,
           (SpiceInt)DSK_MINIMAL_VOXLSZ,
           SPICETRUE,
           (SpiceInt)DSK_MINIMAL_SPXISZ,
           work,
           spaixd,
           spaixi);

  free(work);

  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in dskmi2_c");
  }

  if (SPICE_DSK02_IXDFIX <= 0 || DSK_MINIMAL_SPXISZ <= 0 ||
      spaixd[0] != spaixd[0] || spaixi[0] < 0) {
    write_error_json_ex("invalid_request",
                        "spiceCall dskmi2_c expected non-empty outputs",
                        NULL, NULL, NULL, NULL);
    return false;
  }

  return true;
}

static bool v2_execute_dskw02_legacy_call(void) {
  char tempPath[PATH_MAX];
  if (!v2_write_minimal_dsk_file("v2-dskw02", tempPath, sizeof(tempPath))) {
    return false;
  }

  unlink(tempPath);
  return true;
}

static bool v2_execute_read_virtual_output_call(const char *path) {
  FILE *fp = fopen(path, "rb");
  if (fp == NULL) {
    char detail[384];
    snprintf(detail, sizeof(detail), "%s (%s)", path, strerror(errno));
    write_error_json_ex("invalid_request",
                        "spiceCall readVirtualOutput failed to open file",
                        detail, NULL, NULL, NULL);
    return false;
  }

  if (fseek(fp, 0, SEEK_END) != 0) {
    fclose(fp);
    write_error_json_ex("invalid_request",
                        "spiceCall readVirtualOutput could not read file size",
                        path, NULL, NULL, NULL);
    return false;
  }

  long size = ftell(fp);
  fclose(fp);
  if (size <= 0) {
    write_error_json_ex("invalid_request",
                        "spiceCall readVirtualOutput expected non-empty bytes",
                        path, NULL, NULL, NULL);
    return false;
  }

  return true;
}

static bool v2_try_resolve_named_dskb02_value(const char *name,
                                               SpiceInt nv,
                                               SpiceInt np,
                                               SpiceInt nvxtot,
                                               SpiceInt cgscal,
                                               SpiceInt vtxnpl,
                                               SpiceInt voxnpt,
                                               SpiceInt voxnpl,
                                               SpiceInt *out) {
  if (strcmp(name, "nv") == 0) {
    *out = nv;
    return true;
  }
  if (strcmp(name, "np") == 0) {
    *out = np;
    return true;
  }
  if (strcmp(name, "nvxtot") == 0) {
    *out = nvxtot;
    return true;
  }
  if (strcmp(name, "cgscal") == 0) {
    *out = cgscal;
    return true;
  }
  if (strcmp(name, "vtxnpl") == 0) {
    *out = vtxnpl;
    return true;
  }
  if (strcmp(name, "voxnpt") == 0) {
    *out = voxnpt;
    return true;
  }
  if (strcmp(name, "voxnpl") == 0) {
    *out = voxnpl;
    return true;
  }

  return false;
}

static bool v2_emit_named_dskb02_outputs(const char *json,
                                         const jsmntok_t *tokens,
                                         int tokenCount,
                                         int outMapTok,
                                         V2RefEntry *refs,
                                         int *refCount,
                                         SpiceInt nv,
                                         SpiceInt np,
                                         SpiceInt nvxtot,
                                         SpiceInt cgscal,
                                         SpiceInt vtxnpl,
                                         SpiceInt voxnpt,
                                         SpiceInt voxnpl) {
  const int pairCount = jsmn_object_pair_count(&tokens[outMapTok]);
  if (pairCount < 0) {
    write_error_json_ex("invalid_request", "spiceCall out map parse error", NULL,
                        NULL, NULL, NULL);
    return false;
  }

  int idx = outMapTok + 1;
  for (int i = 0; i < pairCount; i++) {
    int keyTok = idx;
    int valueTok = idx + 1;
    if (valueTok >= tokenCount || tokens[keyTok].type != JSMN_STRING ||
        tokens[valueTok].type != JSMN_STRING) {
      write_error_json_ex("invalid_request", "spiceCall out map parse error", NULL,
                          NULL, NULL, NULL);
      return false;
    }

    char *outName = NULL;
    char *refName = NULL;
    if (!v2_strdup_json_token(json, &tokens[keyTok], &outName) ||
        !v2_strdup_json_token(json, &tokens[valueTok], &refName)) {
      free(outName);
      free(refName);
      return false;
    }

    SpiceInt value = 0;
    if (!v2_try_resolve_named_dskb02_value(outName,
                                            nv,
                                            np,
                                            nvxtot,
                                            cgscal,
                                            vtxnpl,
                                            voxnpt,
                                            voxnpl,
                                            &value)) {
      write_error_json_ex("invalid_args",
                          "Unsupported dskb02 named out param",
                          outName,
                          NULL,
                          NULL,
                          NULL);
      free(outName);
      free(refName);
      return false;
    }

    bool ok = v2_add_ref_int(refs, refCount, refName, value);
    free(outName);
    free(refName);
    if (!ok) {
      return false;
    }

    idx = jsmn_skip_subtree(tokens, valueTok, tokenCount);
    if (idx < 0) {
      write_error_json_ex("invalid_request", "spiceCall out map parse error", NULL,
                          NULL, NULL, NULL);
      return false;
    }
  }

  return true;
}

static bool v2_invoke_card_c(const V2SpiceCallInvokeContext *context) {
  SpiceInt value =
      card_c(&context->refs[context->resolved->refIndices[0]].cell);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in card_c");
  }

  return v2_add_ref_int(context->refs,
                        context->refCount,
                        context->asRefName,
                        value);
}

static bool v2_invoke_size_c(const V2SpiceCallInvokeContext *context) {
  SpiceInt value =
      size_c(&context->refs[context->resolved->refIndices[0]].cell);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in size_c");
  }

  return v2_add_ref_int(context->refs,
                        context->refCount,
                        context->asRefName,
                        value);
}

static bool v2_invoke_scard_c(const V2SpiceCallInvokeContext *context) {
  scard_c(context->resolved->intValues[0],
           &context->refs[context->resolved->refIndices[1]].cell);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in scard_c");
  }

  return true;
}

static bool v2_invoke_ssize_c(const V2SpiceCallInvokeContext *context) {
  ssize_c(context->resolved->intValues[0],
           &context->refs[context->resolved->refIndices[1]].cell);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in ssize_c");
  }

  return true;
}

static bool v2_invoke_valid_c(const V2SpiceCallInvokeContext *context) {
  valid_c(context->resolved->intValues[0],
           context->resolved->intValues[1],
           &context->refs[context->resolved->refIndices[2]].cell);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in valid_c");
  }

  return true;
}

static bool v2_invoke_dskobj_c(const V2SpiceCallInvokeContext *context) {
  dskobj_c(context->resolved->pathValues[0],
           &context->refs[context->resolved->refIndices[1]].cell);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in dskobj_c");
  }

  return true;
}

static bool v2_invoke_dsksrf_c(const V2SpiceCallInvokeContext *context) {
  dsksrf_c(context->resolved->pathValues[0],
           context->resolved->intValues[1],
           &context->refs[context->resolved->refIndices[2]].cell);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in dsksrf_c");
  }

  return true;
}

static bool v2_invoke_dskgd_c(const V2SpiceCallInvokeContext *context) {
  SpiceDSKDescr descriptor;
  memset(&descriptor, 0, sizeof(descriptor));

  dskgd_c(context->refs[context->resolved->refIndices[0]].handleValue,
          &context->refs[context->resolved->refIndices[1]].dlaDescrValue,
          &descriptor);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in dskgd_c");
  }

  return v2_add_ref_dsk_descr(context->refs,
                              context->refCount,
                              context->asRefName,
                              &descriptor);
}

static bool v2_invoke_dskb02_c(const V2SpiceCallInvokeContext *context) {
  SpiceInt nv = 0;
  SpiceInt np = 0;
  SpiceInt nvxtot = 0;
  SpiceDouble vtxbds[3][2];
  SpiceDouble voxsiz = 0.0;
  SpiceDouble voxori[3];
  SpiceInt vgrext[3];
  SpiceInt cgscal = 0;
  SpiceInt vtxnpl = 0;
  SpiceInt voxnpt = 0;
  SpiceInt voxnpl = 0;

  dskb02_c(context->refs[context->resolved->refIndices[0]].handleValue,
           &context->refs[context->resolved->refIndices[1]].dlaDescrValue,
           &nv,
           &np,
           &nvxtot,
           vtxbds,
           &voxsiz,
           voxori,
           vgrext,
           &cgscal,
           &vtxnpl,
           &voxnpt,
           &voxnpl);
  if (failed_c() == SPICETRUE) {
    return v2_write_spice_failure("SPICE error in dskb02_c");
  }

  return v2_emit_named_dskb02_outputs(context->json,
                                      context->tokens,
                                      context->tokenCount,
                                      context->outMapTok,
                                      context->refs,
                                      context->refCount,
                                      nv,
                                      np,
                                      nvxtot,
                                      cgscal,
                                      vtxnpl,
                                      voxnpt,
                                      voxnpl);
}

static bool v2_invoke_dskmi2_c(const V2SpiceCallInvokeContext *context) {
  (void)context;
  return v2_execute_dskmi2_legacy_call();
}

static bool v2_invoke_dskopn_c(const V2SpiceCallInvokeContext *context) {
  (void)context;
  return v2_execute_dskopn_legacy_call();
}

static bool v2_invoke_dskw02_c(const V2SpiceCallInvokeContext *context) {
  (void)context;
  return v2_execute_dskw02_legacy_call();
}

static bool v2_invoke_readVirtualOutput(const V2SpiceCallInvokeContext *context) {
  return v2_execute_read_virtual_output_call(context->resolved->pathValues[0]);
}

typedef bool (*V2SpiceCallInvokerFn)(const V2SpiceCallInvokeContext *context);

typedef struct {
  const char *name;
  V2SpiceCallInvokerFn invoke;
} V2SpiceCallInvokerEntry;

static const V2SpiceCallInvokerEntry V2_SPICE_CALL_INVOKER_REGISTRY[] = {
    {.name = "card_c", .invoke = v2_invoke_card_c},
    {.name = "size_c", .invoke = v2_invoke_size_c},
    {.name = "scard_c", .invoke = v2_invoke_scard_c},
    {.name = "ssize_c", .invoke = v2_invoke_ssize_c},
    {.name = "valid_c", .invoke = v2_invoke_valid_c},
    {.name = "dskobj_c", .invoke = v2_invoke_dskobj_c},
    {.name = "dsksrf_c", .invoke = v2_invoke_dsksrf_c},
    {.name = "dskgd_c", .invoke = v2_invoke_dskgd_c},
    {.name = "dskb02_c", .invoke = v2_invoke_dskb02_c},
    {.name = "dskmi2_c", .invoke = v2_invoke_dskmi2_c},
    {.name = "dskopn_c", .invoke = v2_invoke_dskopn_c},
    {.name = "dskw02_c", .invoke = v2_invoke_dskw02_c},
    {.name = "readVirtualOutput", .invoke = v2_invoke_readVirtualOutput},
};

static V2SpiceCallInvokerFn v2_lookup_spice_call_invoker(const char *callName) {
  const size_t count =
      sizeof(V2_SPICE_CALL_INVOKER_REGISTRY) /
      sizeof(V2_SPICE_CALL_INVOKER_REGISTRY[0]);

  for (size_t i = 0; i < count; i++) {
    if (strcmp(V2_SPICE_CALL_INVOKER_REGISTRY[i].name, callName) == 0) {
      return V2_SPICE_CALL_INVOKER_REGISTRY[i].invoke;
    }
  }

  return NULL;
}

bool v2_invoke_spice_call(const V2SpiceCallInvokeContext *context) {
  if (context == NULL || context->spec == NULL) {
    write_error_json_ex("unsupported_call", "Unsupported v2 spiceCall", NULL,
                        NULL, NULL, NULL);
    return false;
  }

  const char *callName = context->spec->name != NULL ? context->spec->name : context->callName;
  V2SpiceCallInvokerFn invoker = v2_lookup_spice_call_invoker(callName);
  if (invoker == NULL) {
    write_error_json_ex("unsupported_call", "Unsupported v2 spiceCall",
                        context->callName, NULL, NULL, NULL);
    return false;
  }

  return invoker(context);
}
