// Generated by: pnpm -C packages/parity-checking generate:dispatch-artifacts
// Source catalog: packages/parity-checking/catalogs/function-registry.json

#include "cspice_runner_generated_dispatch_table.h"

const CspiceGeneratedDispatchTableEntry CSPICE_GENERATED_DISPATCH_TABLE[] = {
    { "ephemeris.spkezr", false, CSPICE_GEN_DISPATCH_BEHAVIOR_OUT_PARAMS_STRUCTURED_PAYLOAD },
    { "file-io.dskmi2", false, CSPICE_GEN_DISPATCH_BEHAVIOR_STRING_BUFFER_BOUNDS },
    { "frames.ccifrm", false, CSPICE_GEN_DISPATCH_BEHAVIOR_STRING_BUFFER_BOUNDS },
    { "geometry.occult", false, CSPICE_GEN_DISPATCH_BEHAVIOR_INTEGER_RETURN_SPLIT },
    { "ids-names.bodn2c", false, CSPICE_GEN_DISPATCH_BEHAVIOR_COMPLEX_RETURN_FORM },
    { "time.str2et", false, CSPICE_GEN_DISPATCH_BEHAVIOR_INPUT_MAPPING_SCALAR_OUTPUT },
};

const size_t CSPICE_GENERATED_DISPATCH_TABLE_COUNT =
    sizeof(CSPICE_GENERATED_DISPATCH_TABLE) / sizeof(CSPICE_GENERATED_DISPATCH_TABLE[0]);

const CspiceGeneratedDispatchTableEntry *cspice_generated_dispatch_lookup(const char *fn) {
  if (fn == NULL || fn[0] == '\0') {
    return NULL;
  }

  for (size_t index = 0; index < CSPICE_GENERATED_DISPATCH_TABLE_COUNT; index++) {
    const CspiceGeneratedDispatchTableEntry *entry = &CSPICE_GENERATED_DISPATCH_TABLE[index];
    if (strcmp(entry->fn, fn) == 0) {
      return entry;
    }
  }

  return NULL;
}
