/*
 * AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by: pnpm -C packages/parity-checking run generate:v2-spice-calls
 * Source of truth: catalogs/v2-spice-call-manifest.json
 */

#ifndef CSPICE_RUNNER_V2_SPICE_CALLS_GENERATED_H
#define CSPICE_RUNNER_V2_SPICE_CALLS_GENERATED_H

#include "cspice_runner_common.h"
#include "cspice_runner_json_core.h"
#include "cspice_runner_v2_refs.h"

typedef enum {
  V2_SPICE_CALL_ARG_INT_EXPR = 0,
  V2_SPICE_CALL_ARG_CELL_REF,
  V2_SPICE_CALL_ARG_CELL_OR_WINDOW_REF,
  V2_SPICE_CALL_ARG_PATH_EXPR,
  V2_SPICE_CALL_ARG_DAS_HANDLE_REF,
  V2_SPICE_CALL_ARG_DLA_DESCR_REF,
} V2SpiceCallArgKind;

typedef enum {
  V2_SPICE_CALL_OUTPUT_FORBIDDEN = 0,
  V2_SPICE_CALL_OUTPUT_AS_INT,
  V2_SPICE_CALL_OUTPUT_AS_DSK_DESCR,
  V2_SPICE_CALL_OUTPUT_NAMED_DSKB02,
} V2SpiceCallOutputKind;

typedef enum {
  V2_SPICE_CALL_INVOKE_DIRECT = 0,
  V2_SPICE_CALL_INVOKE_LEGACY_DSKOPN,
  V2_SPICE_CALL_INVOKE_LEGACY_DSKMI2,
  V2_SPICE_CALL_INVOKE_LEGACY_DSKW02,
  V2_SPICE_CALL_INVOKE_READ_VIRTUAL_OUTPUT,
} V2SpiceCallInvokeLane;

#define V2_SPICE_CALL_MAX_ARITY 3

typedef struct {
  const char *name;
  int arity;
  V2SpiceCallArgKind argKinds[V2_SPICE_CALL_MAX_ARITY];
  unsigned int nonNegativeIntArgMask;
  V2SpiceCallOutputKind outputKind;
  V2SpiceCallInvokeLane invokeLane;
} V2SpiceCallSpec;

typedef struct {
  SpiceInt intValues[V2_SPICE_CALL_MAX_ARITY];
  int refIndices[V2_SPICE_CALL_MAX_ARITY];
  char *pathValues[V2_SPICE_CALL_MAX_ARITY];
} V2ResolvedSpiceCallArgs;

typedef struct {
  const char *json;
  const jsmntok_t *tokens;
  int tokenCount;
  const char *callName;
  const V2SpiceCallSpec *spec;
  const char *asRefName;
  int outMapTok;
  V2ResolvedSpiceCallArgs *resolved;
  V2RefEntry *refs;
  int *refCount;
} V2SpiceCallInvokeContext;

const V2SpiceCallSpec *v2_lookup_spice_call_spec(const char *name);
bool v2_invoke_spice_call(const V2SpiceCallInvokeContext *context);

#endif
