name: Setup pnpm + Node
description: Reads pnpm version from package.json#packageManager, installs pnpm, then sets up Node with pnpm caching.

inputs:
  node-version:
    description: Node version to install
    required: true

outputs:
  pnpm-version:
    description: pnpm version read from package.json#packageManager
    value: ${{ steps.pnpm-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Read pnpm version from package.json#packageManager
      id: pnpm-version
      shell: bash
      # Ensure this action works even when the calling workflow/job sets a
      # non-root working directory.
      working-directory: ${{ github.workspace }}
      run: |
        set -euo pipefail

        raw=$(node scripts/read-pnpm-version.cjs)


        # Some environments emit CRLF. Strip any carriage returns at runtime.

        raw=${raw//$'\r'/}
        if [ -z "$raw" ]; then
          echo "pnpm version not found in package.json#packageManager (scripts/read-pnpm-version.cjs returned empty)." >&2
          exit 1
        fi

        # Backwards-compatible parsing:
        # - older scripts may output: `pnpm@<version>`
        # - current scripts output: `<version>`
        if [[ "$raw" == pnpm@* ]]; then
          version=${raw#pnpm@}
        else
          version=$raw
        fi

        if [ -z "$version" ]; then
          echo "Could not determine pnpm version from: '$raw' (expected 'pnpm@<version>' or '<version>')." >&2
          exit 1
        fi

        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Setup pnpm
      # Keep in sync with package.json#packageManager.
      # This must run before setup-node when using `cache: pnpm`.
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        version: ${{ steps.pnpm-version.outputs.version }}
        run_install: false

    - name: Setup Node
      # Requires pnpm to be installed first for `cache: pnpm` to work.
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
