// Generated by: pnpm -C packages/parity-checking generate:dispatch-artifacts
// Source catalog: packages/parity-checking/catalogs/function-registry.json

import type { FunctionRegistryFunctionSpec } from "../dsl/functionRegistryTypes.js";

export type GeneratedDispatchBehaviorClass =
  | "input-mapping-scalar-output"
  | "out-params-structured-payload"
  | "integer-return-split"
  | "complex-return-form"
  | "string-buffer-bounds";

export type GeneratedDispatchTableEntry = FunctionRegistryFunctionSpec & {
  implemented: false;
  behaviorClass: GeneratedDispatchBehaviorClass;
};

export const GENERATED_DISPATCH_TABLE = Object.freeze([
  {
    "key": "ephemeris.spkezr",
    "input": {
      "target": "$.in[0]",
      "et": "$.in[1]",
      "frame": "$.in[2]",
      "abcorr": "$.in[3]",
      "observer": "$.in[4]"
    },
    "output": {
      "payload": {
        "state": "out.state",
        "lightTime": "out.lightTime"
      }
    },
    "implemented": false,
    "behaviorClass": "out-params-structured-payload"
  },
  {
    "key": "file-io.dskmi2",
    "input": {
      "handle": "$.in[0]",
      "dladsc": "$.in[1]",
      "room": "$.in[2]"
    },
    "output": {
      "payload": {
        "spaixd": "out.spaixd",
        "spaixi": "out.spaixi"
      }
    },
    "buffers": {
      "spaixi": {
        "lengthFrom": "$.in[2]",
        "elementType": "spiceInt"
      }
    },
    "implemented": false,
    "behaviorClass": "string-buffer-bounds"
  },
  {
    "key": "frames.ccifrm",
    "input": {
      "frameClass": "$.in[0]",
      "classId": "$.in[1]"
    },
    "output": {
      "payload": {
        "found": "out.found",
        "frameId": "out.frameId",
        "frameName": "out.frameName",
        "centerId": "out.centerId"
      }
    },
    "buffers": {
      "frameName": {
        "bytes": {
          "min": 64,
          "max": 1025
        },
        "elementType": "char"
      }
    },
    "implemented": false,
    "behaviorClass": "string-buffer-bounds"
  },
  {
    "key": "geometry.occult",
    "input": {
      "target1": "$.in[0]",
      "shape1": "$.in[1]",
      "frame1": "$.in[2]",
      "target2": "$.in[3]",
      "shape2": "$.in[4]",
      "frame2": "$.in[5]",
      "abcorr": "$.in[6]",
      "observer": "$.in[7]",
      "et": "$.in[8]"
    },
    "output": {
      "value": {
        "from": "out.occultationCode",
        "type": "spiceInt"
      }
    },
    "implemented": false,
    "behaviorClass": "integer-return-split"
  },
  {
    "key": "ids-names.bodn2c",
    "input": {
      "name": "$.in[0]"
    },
    "output": {
      "payload": {
        "found": "out.found",
        "code": "out.code"
      }
    },
    "implemented": false,
    "behaviorClass": "complex-return-form"
  },
  {
    "key": "time.str2et",
    "input": {
      "utc": "$.in[0]"
    },
    "output": {
      "value": {
        "from": "return",
        "type": "spiceDouble"
      }
    },
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  }
]) as readonly GeneratedDispatchTableEntry[];

const GENERATED_DISPATCH_LOOKUP = new Map<string, GeneratedDispatchTableEntry>(
  GENERATED_DISPATCH_TABLE.map((entry) => [entry.key, entry]),
);

export function lookupGeneratedDispatchTableEntry(fn: string): GeneratedDispatchTableEntry | null {
  return GENERATED_DISPATCH_LOOKUP.get(fn) ?? null;
}
