// Generated by: pnpm -C packages/parity-checking generate:dispatch-artifacts
// Source catalog: packages/parity-checking/catalogs/function-registry.json

import type { FunctionRegistryFunctionSpec } from "../dsl/functionRegistryTypes.js";

export type GeneratedDispatchBehaviorClass =
  | "input-mapping-scalar-output"
  | "out-params-structured-payload"
  | "integer-return-split"
  | "complex-return-form"
  | "string-buffer-bounds";

export type GeneratedDispatchTableEntry = FunctionRegistryFunctionSpec & {
  implemented: false;
  behaviorClass: GeneratedDispatchBehaviorClass;
};

export const GENERATED_DISPATCH_TABLE = Object.freeze([
  {
    "key": "cells-windows.card",
    "input": [
      "size"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.insrtc",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.insrtd",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.insrti",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.scard",
    "input": [
      "size",
      "card"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.size",
    "input": [
      "size"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.ssize",
    "input": [
      "allocSize",
      "newSize"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.valid",
    "input": [
      "allocSize",
      "size",
      "n"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.wncard",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.wnfetd",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.wninsd",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "cells-windows.wnvald",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.axisar",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.georec",
    "input": [
      "arg0",
      "arg1",
      "arg2",
      "arg3",
      "arg4"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.latrec",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.mtxv",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.mxm",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.mxv",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.recgeo",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.reclat",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.recsph",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.rotate",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.rotmat",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.sphrec",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.vadd",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.vcrss",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.vdot",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.vhat",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.vminus",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.vnorm",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.vscl",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "coords-vectors.vsub",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "dsk.dskb02",
    "input": [
      "selector"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "dsk.dskgd",
    "input": [
      "selector"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "dsk.dskobj",
    "input": [],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "dsk.dsksrf",
    "input": [],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ephemeris.spkez",
    "input": [
      "arg0",
      "arg1",
      "arg2",
      "arg3",
      "arg4"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ephemeris.spkezp",
    "input": [
      "arg0",
      "arg1",
      "arg2",
      "arg3",
      "arg4"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ephemeris.spkezr",
    "input": [
      "target",
      "et",
      "frame",
      "abcorr",
      "observer"
    ],
    "output": {
      "payload": {
        "state": "out.state",
        "lightTime": "out.lightTime"
      }
    },
    "implemented": false,
    "behaviorClass": "out-params-structured-payload"
  },
  {
    "key": "ephemeris.spkgeo",
    "input": [
      "arg0",
      "arg1",
      "arg2",
      "arg3"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ephemeris.spkgps",
    "input": [
      "arg0",
      "arg1",
      "arg2",
      "arg3"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ephemeris.spkpds",
    "input": [
      "arg0",
      "arg1",
      "arg2",
      "arg3",
      "arg4",
      "arg5"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ephemeris.spkpos",
    "input": [
      "arg0",
      "arg1",
      "arg2",
      "arg3",
      "arg4"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ephemeris.spksfs",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ephemeris.spkssb",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dafbfs",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dafcls",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.daffna",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dafopr",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dascls",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dasopr",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dlabfs",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dlacls",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dlafns",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dlaopn",
    "input": [
      "arg0",
      "arg1",
      "arg2",
      "arg3"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dskmi2",
    "input": [
      "handle",
      "dladsc",
      "room"
    ],
    "output": {
      "payload": {
        "spaixd": "out.spaixd",
        "spaixi": "out.spaixi"
      }
    },
    "buffers": {
      "spaixi": {
        "lengthFrom": "$.in[2]",
        "elementType": "spiceInt"
      }
    },
    "implemented": false,
    "behaviorClass": "out-params-structured-payload"
  },
  {
    "key": "file-io.dskopn",
    "input": [],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.dskw02",
    "input": [],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.exists",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "file-io.getfat",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "frames.ccifrm",
    "input": [
      "frameClass",
      "classId"
    ],
    "output": {
      "payload": {
        "found": "out.found",
        "frameId": "out.frameId",
        "frameName": "out.frameName",
        "centerId": "out.centerId"
      }
    },
    "buffers": {
      "frameName": {
        "bytes": {
          "min": 64,
          "max": 1025
        },
        "elementType": "char"
      }
    },
    "implemented": false,
    "behaviorClass": "string-buffer-bounds"
  },
  {
    "key": "frames.cidfrm",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "frames.cnmfrm",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "frames.frinfo",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "frames.frmnam",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "frames.namfrm",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "frames.pxform",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "frames.sxform",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ids-names.bodc2n",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ids-names.bodc2s",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ids-names.boddef",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ids-names.bodfnd",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ids-names.bodn2c",
    "input": [
      "name"
    ],
    "output": {
      "payload": {
        "found": "out.found",
        "code": "out.code"
      }
    },
    "implemented": false,
    "behaviorClass": "complex-return-form"
  },
  {
    "key": "ids-names.bods2c",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "ids-names.bodvar",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.cvpool",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.dtpool",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.expool",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.gcpool",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.gdpool",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.gipool",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.gnpool",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.pcpool",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.pdpool",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.pipool",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernel-pool.swpool",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernels.furnsh",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernels.kclear",
    "input": [],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernels.kdata",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernels.kinfo",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernels.kplfrm",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernels.ktotal",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernels.kxtrct",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "kernels.unload",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.deltet",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.et2utc",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.str2et",
    "input": [
      "utc"
    ],
    "output": {
      "value": {
        "from": "return",
        "type": "spiceDouble"
      }
    },
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.timdef",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.timout",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.tkvrsn",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.tparse",
    "input": [
      "arg0"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.tpictr",
    "input": [
      "arg0",
      "arg1"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  },
  {
    "key": "time.unitim",
    "input": [
      "arg0",
      "arg1",
      "arg2"
    ],
    "implemented": false,
    "behaviorClass": "input-mapping-scalar-output"
  }
]) as readonly GeneratedDispatchTableEntry[];

const GENERATED_DISPATCH_LOOKUP = new Map<string, GeneratedDispatchTableEntry>(
  GENERATED_DISPATCH_TABLE.map((entry) => [entry.key, entry]),
);

/** Lookup generated dispatch metadata by canonical function key. */
export function lookupGeneratedDispatchTableEntry(fn: string): GeneratedDispatchTableEntry | null {
  return GENERATED_DISPATCH_LOOKUP.get(fn) ?? null;
}
