// Generated by: pnpm -C packages/parity-checking generate:denylist
// v3 baseline: parity denylist is intentionally empty; coverage is enforced by method-spec baseline checks.

export const PARITY_DENYLIST = [
] as const;
