export const BASELINE_METHOD_SPEC_COVERAGE = 105;
export const BASELINE_CONTRACT_METHOD_COVERAGE = BASELINE_METHOD_SPEC_COVERAGE;
export const BASELINE_CONTRACT_METHOD_COUNT = 162;
export const BASELINE_UNCOVERED_CONTRACT_METHODS =
  BASELINE_CONTRACT_METHOD_COUNT - BASELINE_CONTRACT_METHOD_COVERAGE;
