import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { parseFunctionRegistryCatalog } from "../src/dsl/functionRegistryValidate.js";

import type {
  FunctionRegistryBehaviorClass,
  FunctionRegistryCatalog,
  NormalizedFunctionRegistryFunctionSpec,
} from "../src/dsl/functionRegistryTypes.js";

type GeneratedDispatchArtifactEntry = NormalizedFunctionRegistryFunctionSpec;

function stableSort(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");

const functionRegistryPath = path.resolve(packageRoot, "catalogs/function-registry.json");
const tsOutputPath = path.resolve(packageRoot, "src/runners/generatedDispatchTable.generated.ts");
const nativeHeaderPath = path.resolve(
  packageRoot,
  "native/src/cspice_runner_generated_dispatch_table.h",
);
const nativeSourcePath = path.resolve(
  packageRoot,
  "native/src/cspice_runner_generated_dispatch_table.c",
);

function readFunctionRegistryCatalog(): FunctionRegistryCatalog {
  const raw = fs.readFileSync(functionRegistryPath, "utf8");
  const parsed = JSON.parse(raw) as unknown;
  return parseFunctionRegistryCatalog(parsed);
}

function cloneEntry(entry: GeneratedDispatchArtifactEntry): GeneratedDispatchArtifactEntry {
  return {
    key: entry.key,
    input: [...entry.input],
    ...(entry.output === undefined
      ? {}
      : {
          output:
            "value" in entry.output
              ? {
                  value: {
                    from: entry.output.value.from,
                    ...(entry.output.value.type === undefined
                      ? {}
                      : {
                          type: entry.output.value.type,
                        }),
                  },
                }
              : {
                  payload: { ...entry.output.payload },
                },
        }),
    ...(entry.buffers === undefined
      ? {}
      : {
          buffers: Object.fromEntries(
            Object.entries(entry.buffers).map(([bufferName, bufferSpec]) => [
              bufferName,
              "bytes" in bufferSpec
                ? {
                    bytes: { ...bufferSpec.bytes },
                    ...(bufferSpec.elementType === undefined
                      ? {}
                      : {
                          elementType: bufferSpec.elementType,
                        }),
                  }
                : {
                    lengthFrom: bufferSpec.lengthFrom,
                    ...(bufferSpec.elementType === undefined
                      ? {}
                      : {
                          elementType: bufferSpec.elementType,
                        }),
                  },
            ]),
          ),
        }),
    behaviorClass: entry.behaviorClass,
    implemented: entry.implemented,
    ...(entry.executable === undefined
      ? {}
      : {
          executable: {
            ts: {
              method: entry.executable.ts.method,
            },
            native: {
              handler: entry.executable.native.handler,
            },
          },
        }),
    ...(entry.overrideReason === undefined ? {} : { overrideReason: entry.overrideReason }),
  };
}

function buildEntries(catalog: FunctionRegistryCatalog): GeneratedDispatchArtifactEntry[] {
  return [...catalog.functions]
    .sort((a, b) => stableSort(a.key, b.key))
    .map((spec) => cloneEntry(spec));
}

function renderGeneratedTs(entries: GeneratedDispatchArtifactEntry[]): string {
  const tableJson = JSON.stringify(entries, null, 2);
  const tsDispatchMethodLookup = Object.fromEntries(
    entries
      .filter((entry) => entry.implemented)
      .map((entry) => [entry.key, entry.executable?.ts.method ?? null])
      .filter((entry): entry is [string, string] => entry[1] !== null),
  );

  const tsDispatchMethodJson = JSON.stringify(tsDispatchMethodLookup, null, 2);

  return [
    "// Generated by: pnpm -C packages/parity-checking generate:dispatch-artifacts",
    "// Source catalog: packages/parity-checking/catalogs/function-registry.json",
    "",
    'import type {',
    '  FunctionRegistryBehaviorClass,',
    '  NormalizedFunctionRegistryFunctionSpec,',
    '} from "../dsl/functionRegistryTypes.js";',
    "",
    "export type GeneratedDispatchBehaviorClass = FunctionRegistryBehaviorClass;",
    "",
    "export type GeneratedDispatchTableEntry = NormalizedFunctionRegistryFunctionSpec;",
    "",
    `export const GENERATED_DISPATCH_TABLE = Object.freeze(${tableJson}) as readonly GeneratedDispatchTableEntry[];`,
    "",
    "const GENERATED_DISPATCH_LOOKUP = new Map<string, GeneratedDispatchTableEntry>(",
    "  GENERATED_DISPATCH_TABLE.map((entry) => [entry.key, entry]),",
    ");",
    "",
    `const GENERATED_TS_DISPATCH_METHODS = Object.freeze(${tsDispatchMethodJson}) as Readonly<Record<string, string>>;`,
    "",
    "/** Lookup generated dispatch metadata by canonical function key. */",
    "export function lookupGeneratedDispatchTableEntry(fn: string): GeneratedDispatchTableEntry | null {",
    "  return GENERATED_DISPATCH_LOOKUP.get(fn) ?? null;",
    "}",
    "",
    "/** Lookup generated TS callable method name for implemented functions. */",
    "export function lookupGeneratedTsDispatchMethod(fn: string): string | null {",
    "  return GENERATED_TS_DISPATCH_METHODS[fn] ?? null;",
    "}",
    "",
  ].join("\n");
}

function renderNativeHeader(): string {
  return [
    "#ifndef CSPICE_RUNNER_GENERATED_DISPATCH_TABLE_H",
    "#define CSPICE_RUNNER_GENERATED_DISPATCH_TABLE_H",
    "",
    '#include "cspice_runner_common.h"',
    "",
    "typedef enum {",
    "  CSPICE_GEN_DISPATCH_BEHAVIOR_INPUT_MAPPING_SCALAR_OUTPUT = 0,",
    "  CSPICE_GEN_DISPATCH_BEHAVIOR_OUT_PARAMS_STRUCTURED_PAYLOAD = 1,",
    "  CSPICE_GEN_DISPATCH_BEHAVIOR_INTEGER_RETURN_SPLIT = 2,",
    "  CSPICE_GEN_DISPATCH_BEHAVIOR_COMPLEX_RETURN_FORM = 3,",
    "  CSPICE_GEN_DISPATCH_BEHAVIOR_STRING_BUFFER_BOUNDS = 4,",
    "} CspiceGeneratedDispatchBehaviorClass;",
    "",
    "typedef struct {",
    "  const char *fn;",
    "  bool implemented;",
    "  CspiceGeneratedDispatchBehaviorClass behaviorClass;",
    "  const char *nativeHandler;",
    "} CspiceGeneratedDispatchTableEntry;",
    "",
    "extern const CspiceGeneratedDispatchTableEntry CSPICE_GENERATED_DISPATCH_TABLE[];",
    "extern const size_t CSPICE_GENERATED_DISPATCH_TABLE_COUNT;",
    "",
    "const CspiceGeneratedDispatchTableEntry *cspice_generated_dispatch_lookup(const char *fn);",
    "",
    "#endif",
    "",
  ].join("\n");
}

function nativeBehaviorEnum(behaviorClass: FunctionRegistryBehaviorClass): string {
  if (behaviorClass === "input-mapping-scalar-output") {
    return "CSPICE_GEN_DISPATCH_BEHAVIOR_INPUT_MAPPING_SCALAR_OUTPUT";
  }

  if (behaviorClass === "out-params-structured-payload") {
    return "CSPICE_GEN_DISPATCH_BEHAVIOR_OUT_PARAMS_STRUCTURED_PAYLOAD";
  }

  if (behaviorClass === "integer-return-split") {
    return "CSPICE_GEN_DISPATCH_BEHAVIOR_INTEGER_RETURN_SPLIT";
  }

  if (behaviorClass === "complex-return-form") {
    return "CSPICE_GEN_DISPATCH_BEHAVIOR_COMPLEX_RETURN_FORM";
  }

  return "CSPICE_GEN_DISPATCH_BEHAVIOR_STRING_BUFFER_BOUNDS";
}

function renderNativeSource(entries: GeneratedDispatchArtifactEntry[]): string {
  const tableLines = entries.map((entry) => {
    const implementedLiteral = entry.implemented ? "true" : "false";
    const nativeHandlerLiteral =
      entry.implemented && entry.executable !== undefined
        ? `\"${entry.executable.native.handler}\"`
        : "NULL";

    return `    { \"${entry.key}\", ${implementedLiteral}, ${nativeBehaviorEnum(entry.behaviorClass)}, ${nativeHandlerLiteral} },`;
  });

  return [
    "// Generated by: pnpm -C packages/parity-checking generate:dispatch-artifacts",
    "// Source catalog: packages/parity-checking/catalogs/function-registry.json",
    "",
    '#include "cspice_runner_generated_dispatch_table.h"',
    "",
    "const CspiceGeneratedDispatchTableEntry CSPICE_GENERATED_DISPATCH_TABLE[] = {",
    ...tableLines,
    "};",
    "",
    "const size_t CSPICE_GENERATED_DISPATCH_TABLE_COUNT =",
    "    sizeof(CSPICE_GENERATED_DISPATCH_TABLE) / sizeof(CSPICE_GENERATED_DISPATCH_TABLE[0]);",
    "",
    "const CspiceGeneratedDispatchTableEntry *cspice_generated_dispatch_lookup(const char *fn) {",
    "  if (fn == NULL || fn[0] == '\\0') {",
    "    return NULL;",
    "  }",
    "",
    "  for (size_t index = 0; index < CSPICE_GENERATED_DISPATCH_TABLE_COUNT; index++) {",
    "    const CspiceGeneratedDispatchTableEntry *entry = &CSPICE_GENERATED_DISPATCH_TABLE[index];",
    "    if (strcmp(entry->fn, fn) == 0) {",
    "      return entry;",
    "    }",
    "  }",
    "",
    "  return NULL;",
    "}",
    "",
  ].join("\n");
}

const catalog = readFunctionRegistryCatalog();
const entries = buildEntries(catalog);

fs.mkdirSync(path.dirname(tsOutputPath), { recursive: true });
fs.writeFileSync(tsOutputPath, renderGeneratedTs(entries), "utf8");

fs.mkdirSync(path.dirname(nativeHeaderPath), { recursive: true });
fs.writeFileSync(nativeHeaderPath, renderNativeHeader(), "utf8");

fs.mkdirSync(path.dirname(nativeSourcePath), { recursive: true });
fs.writeFileSync(nativeSourcePath, renderNativeSource(entries), "utf8");

console.log(`[parity-checking] wrote generated dispatch artifacts (${entries.length} entries)`);
