import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { parse as parseYaml } from "yaml";

type WorkflowKind = "callContract" | "workflow";

type MethodSurfaceEntry = {
  manifestId: string;
  canonicalMethod: string;
  contractMethod: string;
  workflowKind: WorkflowKind;
};

type MethodSurfaceRegistry = {
  schemaVersion: number;
  description?: string;
  methods: MethodSurfaceEntry[];
};

const WORKFLOW_KINDS: readonly WorkflowKind[] = ["callContract", "workflow"] as const;

function stableCompare(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function asRecord(value: unknown, label: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new TypeError(`${label} must be an object`);
  }

  return value as Record<string, unknown>;
}

function asString(value: unknown, label: string): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new TypeError(`${label} must be a non-empty string`);
  }

  return value;
}

function parseEntry(value: unknown, index: number): MethodSurfaceEntry {
  const obj = asRecord(value, `registry.methods[${index}]`);

  const manifestId = asString(obj.manifestId, `registry.methods[${index}].manifestId`);
  const canonicalMethod = asString(
    obj.canonicalMethod,
    `registry.methods[${index}].canonicalMethod`,
  );
  const contractMethod = asString(obj.contractMethod, `registry.methods[${index}].contractMethod`);
  const workflowKind = asString(obj.workflowKind, `registry.methods[${index}].workflowKind`);

  if (!WORKFLOW_KINDS.includes(workflowKind as WorkflowKind)) {
    throw new TypeError(
      `registry.methods[${index}].workflowKind must be one of ${WORKFLOW_KINDS.join(", ")} (got ${JSON.stringify(workflowKind)})`,
    );
  }

  return {
    manifestId,
    canonicalMethod,
    contractMethod,
    workflowKind: workflowKind as WorkflowKind,
  };
}

function parseRegistry(value: unknown): MethodSurfaceRegistry {
  const obj = asRecord(value, "registry");

  if (obj.schemaVersion !== 1) {
    throw new TypeError(`registry.schemaVersion must be 1 (got ${JSON.stringify(obj.schemaVersion)})`);
  }

  if (!Array.isArray(obj.methods)) {
    throw new TypeError("registry.methods must be an array");
  }

  const methods = obj.methods.map((entry, index) => parseEntry(entry, index));

  const seenCanonical = new Set<string>();
  const seenManifest = new Set<string>();
  for (const entry of methods) {
    if (seenCanonical.has(entry.canonicalMethod)) {
      throw new TypeError(`Duplicate canonicalMethod in method-surface registry: ${entry.canonicalMethod}`);
    }
    if (seenManifest.has(entry.manifestId)) {
      throw new TypeError(`Duplicate manifestId in method-surface registry: ${entry.manifestId}`);
    }

    seenCanonical.add(entry.canonicalMethod);
    seenManifest.add(entry.manifestId);
  }

  const sorted = [...methods].sort((a, b) =>
    stableCompare(a.canonicalMethod, b.canonicalMethod) || stableCompare(a.manifestId, b.manifestId),
  );

  const sortedCanonical = sorted.map((entry) => entry.canonicalMethod);
  const inputCanonical = methods.map((entry) => entry.canonicalMethod);
  if (JSON.stringify(sortedCanonical) !== JSON.stringify(inputCanonical)) {
    throw new TypeError(
      "registry.methods must be sorted by canonicalMethod. Run: pnpm -C packages/parity-checking run sync:method-surface",
    );
  }

  return {
    schemaVersion: 1,
    ...(typeof obj.description === "string" ? { description: obj.description } : {}),
    methods,
  };
}

function renderTs(registry: MethodSurfaceRegistry): string {
  const lines: string[] = [];
  lines.push("// Generated by: pnpm -C packages/parity-checking run generate:method-surface-artifacts");
  lines.push("// Source of truth: packages/parity-checking/registry/method-surface.yml");
  lines.push("");
  lines.push('export type MethodSurfaceWorkflowKind = "callContract" | "workflow";');
  lines.push("");
  lines.push("export type MethodSurfaceEntry = {");
  lines.push("  manifestId: string;");
  lines.push("  canonicalMethod: string;");
  lines.push("  contractMethod: string;");
  lines.push("  workflowKind: MethodSurfaceWorkflowKind;");
  lines.push("};");
  lines.push("");
  lines.push(`export const METHOD_SURFACE_SCHEMA_VERSION = ${registry.schemaVersion} as const;`);
  lines.push("");
  lines.push("export const METHOD_SURFACE_REGISTRY: ReadonlyArray<MethodSurfaceEntry> = [");

  for (const method of registry.methods) {
    lines.push("  {");
    lines.push(`    manifestId: ${JSON.stringify(method.manifestId)},`);
    lines.push(`    canonicalMethod: ${JSON.stringify(method.canonicalMethod)},`);
    lines.push(`    contractMethod: ${JSON.stringify(method.contractMethod)},`);
    lines.push(`    workflowKind: ${JSON.stringify(method.workflowKind)},`);
    lines.push("  },");
  }

  lines.push("] as const;");
  lines.push("");
  lines.push(
    "export const METHOD_SURFACE_REGISTRY_BY_CANONICAL = new Map(METHOD_SURFACE_REGISTRY.map((entry) => [entry.canonicalMethod, entry] as const));",
  );
  lines.push("");
  lines.push(
    "export const METHOD_SURFACE_CALL_CONTRACT_CANONICAL = new Set(METHOD_SURFACE_REGISTRY.filter((entry) => entry.workflowKind === \"callContract\").map((entry) => entry.canonicalMethod));",
  );
  lines.push("");

  return `${lines.join("\n")}\n`;
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");

const registryPath = path.resolve(packageRoot, "registry/method-surface.yml");
const jsonOutPath = path.resolve(packageRoot, "catalogs/method-surface.json");
const tsOutPath = path.resolve(packageRoot, "src/generated/methodSurfaceRegistry.ts");

const registryRaw = fs.readFileSync(registryPath, "utf8");
const parsed = parseRegistry(parseYaml(registryRaw));

fs.mkdirSync(path.dirname(jsonOutPath), { recursive: true });
fs.writeFileSync(jsonOutPath, `${JSON.stringify(parsed, null, 2)}\n`, "utf8");

fs.mkdirSync(path.dirname(tsOutPath), { recursive: true });
fs.writeFileSync(tsOutPath, renderTs(parsed), "utf8");

console.log(`[parity-checking] wrote method surface artifacts (${parsed.methods.length} methods)`);
console.log(`- ${jsonOutPath}`);
console.log(`- ${tsOutPath}`);
