import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { parse as parseYaml } from "yaml";

function stableSort(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function canonicalMethodFromSpecData(data: unknown, filePath: string): string {
  if (!isRecord(data)) {
    throw new Error(`Method spec must be an object: ${filePath}`);
  }

  if (typeof data.canonicalMethod === "string" && data.canonicalMethod.trim() !== "") {
    return data.canonicalMethod;
  }

  const contract = data.contract;
  if (
    isRecord(contract) &&
    typeof contract.canonicalMethod === "string" &&
    contract.canonicalMethod.trim() !== ""
  ) {
    return contract.canonicalMethod;
  }

  throw new Error(`Method spec missing canonicalMethod: ${filePath}`);
}

function discoverYamlFiles(rootDir: string): string[] {
  const out: string[] = [];
  if (!fs.existsSync(rootDir)) {
    return out;
  }

  const visit = (dir: string) => {
    const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => stableSort(a.name, b.name));
    for (const entry of entries) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        visit(abs);
      } else if (entry.isFile() && (entry.name.endsWith(".yml") || entry.name.endsWith(".yaml"))) {
        out.push(abs);
      }
    }
  };

  visit(rootDir);
  return out;
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");

const contractCatalogPath = path.resolve(packageRoot, "catalogs/contract-methods.json");
const methodSpecsRoot = path.resolve(packageRoot, "specs/methods");
const denylistJsonPath = path.resolve(packageRoot, "catalogs/parity-denylist.json");
const denylistTsPath = path.resolve(packageRoot, "catalogs/parity-denylist.ts");

const contractCatalog = JSON.parse(fs.readFileSync(contractCatalogPath, "utf8")) as string[];
if (!Array.isArray(contractCatalog)) {
  throw new Error(`Contract catalog is not a JSON array: ${contractCatalogPath}`);
}

const coveredCanonical = new Set<string>();
for (const filePath of discoverYamlFiles(methodSpecsRoot)) {
  const data = parseYaml(fs.readFileSync(filePath, "utf8"));
  coveredCanonical.add(canonicalMethodFromSpecData(data, filePath));
}

const denylist = contractCatalog
  .filter((method) => !coveredCanonical.has(method))
  .sort(stableSort);

fs.mkdirSync(path.dirname(denylistJsonPath), { recursive: true });
fs.writeFileSync(denylistJsonPath, `${JSON.stringify(denylist, null, 2)}\n`, "utf8");

const tsLines = [
  "// Generated by: pnpm -C packages/parity-checking generate:denylist",
  "// Source catalogs: contract-methods.json - method specs canonical coverage",
  "",
  "export const PARITY_DENYLIST = [",
  ...denylist.map((entry) => `  ${JSON.stringify(entry)},`),
  "] as const;",
  "",
];

fs.writeFileSync(denylistTsPath, `${tsLines.join("\n")}`, "utf8");

console.log(
  `[parity-checking] wrote denylist (${denylist.length}) -> ${denylistJsonPath} and ${denylistTsPath}`,
);
